services:

  Apps.mooc.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.mooc.controllers.CoursePutController:
    class: ../../controllers/CoursePutController
    arguments: [" Mooc.Courses.application.CourseCreator"]
  
  Apps.mooc.controllers.NotePutController:
    class: ../../controllers/NotePutController
    arguments: ["@Mooc.Notes.application.NoteCreator"]