services: 

  Mooc.Courses.application.CurseCreator:
    class: ../../../../../Contexts/Mooc/Course/application/CourseCreator
    arguments: ["@Mooc.Course.domain.CurseRepository"]

  Mooc.Curses.domain.CurseRepository:
    class: ../../../../../Contexts/Mooc/Course/infrastructure/persistence/FileNoteRepository
    arguments: [""]