services: 

  Mooc.Curses.application.CurseCreator:
    class: ../../../../../Contexts/Mooc/Curse/application/CurseCreator
    arguments: ["@Mooc.Curse.domain.NoteRepository"]

  Mooc.Curses.domain.CurseRepository:
    class: ../../../../../Contexts/Mooc/Curse/infrastructure/persistence/FileNoteRepository
    arguments: [""]