services: 

  Mooc.Curses.application.CurseCreator:
    class: ../../../../../Contexts/Mooc/Course/application/CurseCreator
    arguments: ["@Mooc.Course.domain.CurseRepository"]

  Mooc.Curses.domain.CurseRepository:
    class: ../../../../../Contexts/Mooc/Curse/infrastructure/persistence/FileNoteRepository
    arguments: [""]